name: Build Image

on:
  workflow_dispatch:
  push:
    tags:
    - "v*.*.*"
    branches:
    - main
  pull_request:
    types:
    - opened
    - reopened

jobs:
  build:
    runs-on: alpine-tokyo
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - name: Checkout
      uses: https://github.com/actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        VERSION=latest
        REGISTRY_SERVER=${GITHUB_SERVER_URL:8}
        REGISTRY_IMAGE=${REGISTRY_SERVER}/${GITHUB_REPOSITORY}
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        # v1.0.0
        TAGS="${REGISTRY_IMAGE}:${VERSION}"
        # v1.0.0,v1
        TAGS="${TAGS},${REGISTRY_IMAGE}:${VERSION%%.*}"
        if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          # :v1.0.0,:v1,:latest
          TAGS="${TAGS},${REGISTRY_IMAGE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=registry_server::${REGISTRY_SERVER}

        if [ "${{github.event_name}}" == "pull_request" ]; then
          echo ::set-output name=push::false
          # echo ::set-output name=cache_from::"type=registry,ref=${REGISTRY_IMAGE}:buildcache"
          # echo ::set-output name=cache_to::""
        else
          echo ::set-output name=push::true
          # echo ::set-output name=cache_from::"type=registry,ref=${REGISTRY_IMAGE}:buildcache"
          # echo ::set-output name=cache_to::"type=registry,ref=${REGISTRY_IMAGE}:buildcache,mode=max"
        fi

    - name: Set up QEMU
      uses: https://github.com/docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: https://github.com/docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: https://github.com/docker/login-action@v1
      with:
        registry: ${{ steps.prep.outputs.registry_server }}
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_TOKEN }}

    - name: Build and Push
      id: docker_build
      uses: https://github.com/docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ steps.prep.outputs.push }}
        tags: ${{ steps.prep.outputs.tags }}
        build-args: |
          IMAGE_SOURCE=$GITHUB_SERVER_URL/${{ github.repository }}
        # cache-from: ${{ steps.prep.outputs.cache_from }}
        # cache-to: ${{ steps.prep.outputs.cache_to }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
